[tool.poetry]
name = "type-annotations"
version = "0.1.0"
description = ""
authors = ["Sergei Maslov <s.maslov@bi.zone>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disable_error_code=["empty-body"]
